name: Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build binaries
        run: |
          mkdir -p dist

          GOOS=linux GOARCH=amd64 go build -o dist/linux-amd64/lc
          GOOS=windows GOARCH=amd64 go build -o dist/windows-amd64/lc.exe
          GOOS=darwin GOARCH=amd64 go build -o dist/darwin-amd64/lc

      - name: Generate checksums
        run: |
          cd dist
          find . -type f -exec sha256sum {} \; > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/checksums.txt
            dist/**/*